language: java
jdk:
  - oraclejdk8
install: true
script:
  - ./gradlew :antlr-kotlin-runtime-jvm:test
  - ./gradlew :antlr-kotlin-runtime-js:test
  - ./gradlew :antlr-kotlin-runtime-common:install
  - ./gradlew :antlr-kotlin-runtime-jvm:install
  - ./gradlew :antlr-kotlin-runtime-js:install
  - ./gradlew :antlr-kotlin-target:install
  - ./gradlew :antlr-kotlin-gradle-plugin:install
  - cd antlr-kotlin-runtime-examples-jvm && ../gradlew check && cd ..
  - cd antlr-kotlin-runtime-examples-js && ../gradlew check && cd ..

  