[versions]
kotlin = "2.1.20-Beta1"
kotlin-wrappers = "1.0.0-pre.748"
kotlinx-io = "0.6.0"
kotlinx-benchmark = "0.4.13"
kotlinx-resources = "0.10.0"
antlr4 = "4.13.1"
dokka = "1.9.20"
researchgate-release = "3.1.0"
maven-publish = "0.30.0"
gradle-plugin-publish = "1.3.0"

[libraries]
kotlin-wrappers-bom = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-wrappers-bom", version.ref = "kotlin-wrappers" }
kotlin-wrappers-kotlin-js = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-js" }
kotlin-wrappers-kotlin-node = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-node" }
kotlinx-io-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-benchmark = { group = "org.jetbrains.kotlinx", name = "kotlinx-benchmark-runtime", version.ref = "kotlinx-benchmark" }
kotlinx-resources = { group = "com.goncalossilva", name = "resources", version.ref = "kotlinx-resources" }
antlr4 = { group = "org.antlr", name = "antlr4", version.ref = "antlr4" }

# Gradle
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-plugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
maven-publish-plugin = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "maven-publish" }
gradle-plugin-publish-plugin = { group = "com.gradle.publish", name = "plugin-publish-plugin", version.ref = "gradle-plugin-publish" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinx-benchmark" }
kotlinx-resources = { id = "com.goncalossilva.resources", version.ref = "kotlinx-resources" }
researchgate-release = { id = "net.researchgate.release", version.ref = "researchgate-release" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
